### ISSUE TITLE
`checkCompletion` error

### ISSUE THREAD

**Issue by gvallee** [gvallee/validation_tool#4]
I saw that error in the context of OpenHPCA, using version 1.3.0:
```
runtime error: slice bounds out of range [1:0]

goroutine 7 [running]:
github.com/gvallee/validation_tool/pkg/experiments.(*Runtime).checkCompletions(0xc000194230, 0x0)
	/global/home/users/geoffroy/go/pkg/mod/github.com/gvallee/validation_tool@v1.3.0/pkg/experiments/experiments.go:621 +0x4b2
github.com/gvallee/validation_tool/pkg/experiments.(*Runtime).checkCompletions(0xc000194230, 0x0)
	/global/home/users/geoffroy/go/pkg/mod/github.com/gvallee/validation_tool@v1.3.0/pkg/experiments/experiments.go:625 +0x234
github.com/gvallee/validation_tool/pkg/experiments.(*Runtime).checkCompletions(0xc000194230, 0x0)
	/global/home/users/geoffroy/go/pkg/mod/github.com/gvallee/validation_tool@v1.3.0/pkg/experiments/experiments.go:625 +0x234
github.com/gvallee/validation_tool/pkg/experiments.(*Runtime).serveJobQueue(0xc000194230, 0x0, 0x0)
	/global/home/users/geoffroy/go/pkg/mod/github.com/gvallee/validation_tool@v1.3.0/pkg/experiments/experiments.go:663 +0x136
github.com/gvallee/validation_tool/pkg/experiments.(*Runtime).Start.func1(0xc000194230)
	/global/home/users/geoffroy/go/pkg/mod/github.com/gvallee/validation_tool@v1.3.0/pkg/experiments/experiments.go:908 +0x10f
created by github.com/gvallee/validation_tool/pkg/experiments.(*Runtime).Start
	/global/home/users/geoffroy/go/pkg/mod/github.com/gvallee/validation_tool@v1.3.0/pkg/experiments/experiments.go:896 +0x4f
```

**Comment by gvallee** [comment]
Fixed in v1.3.1
